In [3]:
!pip install opencv-python


   ---------------------------------------- 0.0/39.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/39.5 MB ? eta -:--:--
    --------------------------------------- 0.5/39.5 MB 2.1 MB/s eta 0:00:19
   - -------------------------------------- 1.0/39.5 MB 2.1 MB/s eta 0:00:19
   - -------------------------------------- 1.3/39.5 MB 2.0 MB/s eta 0:00:20
   - -------------------------------------- 1.6/39.5 MB 1.7 MB/s eta 0:00:22
   - -------------------------------------- 1.8/39.5 MB 1.6 MB/s eta 0:00:24
   -- ------------------------------------- 2.1/39.5 MB 1.6 MB/s eta 0:00:24
   -- ------------------------------------- 2.4/39.5 MB 1.5 MB/s eta 0:00:25
   -- ------------------------------------- 2.9/39.5 MB 1.6 MB/s eta 0:00:24
   --- ------------------------------------ 3.1/39.5 MB 1.5 MB/s eta 0:00:25
   --- ------------------------------------ 3.4/39.5 MB 1.5 MB/s eta 0:00:24
   --- ------------------------------------ 3.9/39.5 MB 1.6 MB/s eta 0:00:22
   ---- -----


[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import cv2
print(cv2.__version__)


4.11.0


In [9]:
img2 = img.copy()
img2[:,:,2]=0

img_rbg = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

In [10]:
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

In [11]:
print(img_gray)

[[146 156 133 ...  85 102 101]
 [139 153 137 ...  86  98 105]
 [126 133 125 ...  88  92 110]
 ...
 [221 216 204 ... 207 201 186]
 [218 218 202 ... 197 191 178]
 [208 214 209 ... 203 201 189]]


In [14]:
events = [i for i in dir(cv2) if 'EVENT' in i]
print(events)

['EVENT_FLAG_ALTKEY', 'EVENT_FLAG_CTRLKEY', 'EVENT_FLAG_LBUTTON', 'EVENT_FLAG_MBUTTON', 'EVENT_FLAG_RBUTTON', 'EVENT_FLAG_SHIFTKEY', 'EVENT_LBUTTONDBLCLK', 'EVENT_LBUTTONDOWN', 'EVENT_LBUTTONUP', 'EVENT_MBUTTONDBLCLK', 'EVENT_MBUTTONDOWN', 'EVENT_MBUTTONUP', 'EVENT_MOUSEHWHEEL', 'EVENT_MOUSEMOVE', 'EVENT_MOUSEWHEEL', 'EVENT_RBUTTONDBLCLK', 'EVENT_RBUTTONDOWN', 'EVENT_RBUTTONUP']


In [13]:
import matplotlib.pyplot as plt

plt.show(img_gray)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

<>:1: SyntaxWarning: invalid escape sequence '\M'
<>:1: SyntaxWarning: invalid escape sequence '\M'
C:\Users\binhn\AppData\Local\Temp\ipykernel_23160\1471770677.py:1: SyntaxWarning: invalid escape sequence '\M'
  img3= cv2.imread('D:\MSE\HomeWork\Ky 2\IVP501\Book\images\girl.jpeg')


In [22]:
img3_sum = cv2.applyColorMap(img3,cv2.COLORMAP_SUMMER)
img3_ocean = cv2.applyColorMap(img3,cv2.COLORMAP_OCEAN)

In [20]:

if img3 is None:
    print("Không tìm thấy ảnh. Vui lòng kiểm tra lại đường dẫn.")
else:
    cv2.imshow('image', img3_sum)
    cv2.waitKey(0)
    cv2.destroyAllWindows()


In [23]:

if img3 is None:
    print("Không tìm thấy ảnh. Vui lòng kiểm tra lại đường dẫn.")
else:
    cv2.imshow('image', img3_ocean)
    cv2.waitKey(0)
    cv2.destroyAllWindows()


In [4]:
import numpy as np 
img = np.ones((1920,1080,3), dtype= np.uint8)*255
cv2.imshow('White background', img)
# cv2.imsave('White bg.png')
cv2.waitKey()

-1

In [5]:
# tao hinh cn
def draw_rectangle(event, x,y , flags, param):
     global rect_start, rect_end, drawing, image, rect_coords
     if event == cv2.EVENT_LBUTTONDBLCLK: # di chuột
          drawing = True
          rect_stat = (x,y)
     elif event == cv2.EVENT_MOUSEMOVE: # chuột di
          if drawing:
               image_copy = image.copy()
               cv2.rectangle(image_copy, rect_stat, (x,y), (0,255,0),2)
     elif event == cv2.EVENT_LBUTTONUP: # thả chuột
          drawing = False
          rect_end = (x,y)
          cv2.rectangle(image_copy, rect_stat, (x,y), (0,255,0),2)
          cv2.imshow('Draw Rectangle', image)
          

In [ ]:
cv2.namedWindow('Draw Rectangle')
cv2.setMouseCallback('Draw Rectangle', draw_rectangle)
cv2.waitKey()