In [1]:
import pandas as pd
import numpy as np
u = np.array(['Orange', 'Banana', 'Lemon', 'Strawberry'])
v = {'USA': 'New York', 'VietNam': 'HCM City', 'Korea': 'Seoul'}

s1 = pd.Series(u)
s2 = pd.Series(v)
print(u, type(u))
print(s1, type(s1), s1[0], len(s1))
print(s2, type(s2), s2[2], s2['Korea'])
print(s1[1:3])
print(s2[['VietNam', 'Korea']])


['Orange' 'Banana' 'Lemon' 'Strawberry'] <class 'numpy.ndarray'>
0        Orange
1        Banana
2         Lemon
3    Strawberry
dtype: object <class 'pandas.core.series.Series'> Orange 4
USA        New York
VietNam    HCM City
Korea         Seoul
dtype: object <class 'pandas.core.series.Series'> Seoul Seoul
1    Banana
2     Lemon
dtype: object
VietNam    HCM City
Korea         Seoul
dtype: object


C:\Users\Admin\AppData\Local\Temp\ipykernel_29540\1908963904.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s2, type(s2), s2[2], s2['Korea'])


In [2]:
# More Question
# Question : How to update value in the Series by index  ?


In [3]:
u = np.array(['Orange', 'Banana', 'Lemon', 'Strawberry'])
s1 = pd.Series(u)
s1.index = ['12', '13', '14', '15']
s1['12'] = 'Apple1'
s1.loc['0'] = 'Apple2'
print(s1)


12        Apple1
13        Banana
14         Lemon
15    Strawberry
0         Apple2
dtype: object


In [4]:
# Series 2 Conversion
index = pd.DatetimeIndex(
    ['2020-07-04', '2020-08-04', '2021-07-04', '2021-08-04'])
s = pd.Series([0, 1, 2, 3], index=index)

print(s, type(s))
print(s['2020-07-04': '2021-07-04'])
print(s['2020'])


2020-07-04    0
2020-08-04    1
2021-07-04    2
2021-08-04    3
dtype: int64 <class 'pandas.core.series.Series'>
2020-07-04    0
2020-08-04    1
2021-07-04    2
dtype: int64
2020-07-04    0
2020-08-04    1
dtype: int64


In [5]:
# More Question
# Question : Create a Series from beginning date of month to now in index and values are random integers  ?


In [6]:
import datetime as dt
now = dt.datetime.today().strftime("%m/%d/%Y")
beg = '07/01/2021'
index = pd.date_range(start=beg, end=now)

print(index.shape[0])
data = np.random.randint(0, 30, size=index.shape[0])
print(data)
ser = pd.Series(data, index=index)
print(ser)


1263
[ 6  6 17 ...  6 24  2]
2021-07-01     6
2021-07-02     6
2021-07-03    17
2021-07-04     4
2021-07-05     8
              ..
2024-12-10    19
2024-12-11    12
2024-12-12     6
2024-12-13    24
2024-12-14     2
Freq: D, Length: 1263, dtype: int32


In [1]:
# List
lst1 = ["apple", "banana", "cherry", "apple", "cherry"]
lst2 = [1, 5, 7, 9, 3, 1, 5]
lst3 = [True, False, False]
lst4 = ['apple', 5, True, 3.14]
lst5 = list(set(lst1))

print(lst1, type(lst1), len(lst1))
print(lst1, lst2, lst3, lst4, lst5)
print(lst1[0], lst2[-1], lst3[:2], lst4[1:3], 'apple' in lst4)

lst1[3:5] = ['orange', 'coconut']
lst2[-1] = 9
lst3[2] = True
lst4.insert(0, "John")
lst4.append("Hello World")
print(lst1, lst2, lst3, lst4)

lst2.remove(1)
print(lst1 + lst2, lst3)
print("We have " + " ; ".join(lst1))


['apple', 'banana', 'cherry', 'apple', 'cherry'] <class 'list'> 5
['apple', 'banana', 'cherry', 'apple', 'cherry'] [1, 5, 7, 9, 3, 1, 5] [True, False, False] ['apple', 5, True, 3.14] ['cherry', 'banana', 'apple']
apple 5 [True, False] [5, True] True
['apple', 'banana', 'cherry', 'orange', 'coconut'] [1, 5, 7, 9, 3, 1, 9] [True, False, True] ['John', 'apple', 5, True, 3.14, 'Hello World']
['apple', 'banana', 'cherry', 'orange', 'coconut', 5, 7, 9, 3, 1, 9] [True, False, True]
We have apple ; banana ; cherry ; orange ; coconut


In [9]:
# Array
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5, 6, 7])
arr2 = np.array([1.1, 2.5, -3, 4.6, 0, 9])
arr3 = np.array(["Monday", "Tuesday", "Wednesday",
                "Thursday", "Friday", "Saturday", "Sunday"])
arr4 = np.array(["Python", True, 1, 2.5])
arr5 = arr2.copy()

print(arr1, type(arr1), arr1.ndim, len(arr1))
print(arr2, type(arr2), arr2.ndim, len(arr2))
print(arr4, type(arr4), arr4.ndim, len(arr4))
print(arr1[3], arr1[2:5], arr1[::2], arr1[::3], arr1[1::2])
print(arr1.dtype, arr2.dtype, arr3.dtype, arr4.dtype)
print(arr1.max(), arr1.min(), arr1.mean(), arr1.std())

arr4.sort()
print(arr4, arr4.shape)
arr2 = arr2.astype(int)
print(arr2)
arr2 = arr2.astype(bool)
print(arr2)


[1 2 3 4 5 6 7] <class 'numpy.ndarray'> 1 7
[ 1.1  2.5 -3.   4.6  0.   9. ] <class 'numpy.ndarray'> 1 6
['Python' 'True' '1' '2.5'] <class 'numpy.ndarray'> 1 4
4 [3 4 5] [1 3 5 7] [1 4 7] [2 4 6]
int64 float64 <U9 <U32
7 1 4.0 2.0
['1' '2.5' 'Python' 'True'] (4,)
[ 1  2 -3  4  0  9]
[ True  True  True  True False  True]


In [10]:
# More Question
# Question : How create an array of number from 0 to 10 with interval 0.5 ?


In [11]:
# Array
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr2 = np.array([1.5, 2.5, 3.5])
arr3 = np.array([-1.5, -2.5, -3.5])
arr4 = np.array(["Monday", "Tuesday", "Wednesday",
                "Thursday", "Friday", "Saturday", "Sunday"])
arr5 = np.concatenate((arr1, arr2))
arr6 = np.hstack((arr2, arr3))
arr7 = np.vstack((arr2, arr3))
arr8 = np.dstack((arr2, arr3))

print(arr1.reshape(2, 5))
print(arr5)
print(arr6)
print(arr7)
print(arr8)
print(np.array_split(arr4, 3))


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1.   2.   3.   4.   5.   6.   7.   8.   9.  10.   1.5  2.5  3.5]
[ 1.5  2.5  3.5 -1.5 -2.5 -3.5]
[[ 1.5  2.5  3.5]
 [-1.5 -2.5 -3.5]]
[[[ 1.5 -1.5]
  [ 2.5 -2.5]
  [ 3.5 -3.5]]]
[array(['Monday', 'Tuesday', 'Wednesday'], dtype='<U9'), array(['Thursday', 'Friday'], dtype='<U9'), array(['Saturday', 'Sunday'], dtype='<U9')]


In [12]:
# More Question
# Question : How to stack two array in case of not the same size (putting 0 for missing element) ?


In [13]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
A1 = arr1.reshape(2, 5)
print(arr1.reshape(2, 5))

Ae = np.zeros([1, 5])
A2 = np.vstack([A1, Ae])

print(A2)
A3 = np.hstack([np.zeros([3, 1]), A2])
print(A3)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [ 0.  0.  0.  0.  0.]]
[[ 0.  1.  2.  3.  4.  5.]
 [ 0.  6.  7.  8.  9. 10.]
 [ 0.  0.  0.  0.  0.  0.]]


In [14]:
# Array
import numpy as np
import re
arr1 = np.array([1, 2, 3, 4, 5, 4, 4])
arr2 = np.array(["Monday", "Tuesday", "Wednesday",
                "Thursday", "Friday", "Saturday", "Sunday"])
pos = np.where(arr1 == 4)
condition = [True, False, True, False, False, False, False]
arr3 = arr2[:3]
filter_arr = arr1 > 4
arr4 = [s for s in arr2 if "es" in s]
arr5 = np.arange(10)
arr6 = np.where(arr5 % 2 == 0, arr5, 0)
r = re.compile('.*ur.*')
arr7 = [line for line in arr2 if r.match(line)]

print(pos, np.where(arr2 == "Thursday"))
print(np.sort(arr1), arr3)
print(filter_arr, arr1[filter_arr], arr4)
print(arr5, arr6, arr7)
print(np.random.randint(15, size=10))
print(np.random.rand(10))


(array([3, 5, 6]),) (array([3]),)
[1 2 3 4 4 4 5] ['Monday' 'Tuesday' 'Wednesday']
[False False False False  True False False] [5] [np.str_('Tuesday'), np.str_('Wednesday')]
[0 1 2 3 4 5 6 7 8 9] [0 0 2 0 4 0 6 0 8 0] [np.str_('Thursday'), np.str_('Saturday')]
[ 1  1  2 13  0  2 10  1 11  7]
[0.1285169  0.78402484 0.28709426 0.14931258 0.24142524 0.5007026
 0.24989605 0.81554304 0.52064586 0.4726215 ]


In [15]:
# More Question
# Question : How to create a random array from 10 to 20 ? How to find element in array beginning with S  ?


In [ ]:
# Matrix
import numpy as np
M1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
M2 = np.array([[1, 0, 0], [0, 2, 0], [0, 0, 1]])
print(M1, "\n",  M2, len(M2))
print(M1 + M2, "\n", M1 - M2)
print(M1.dot(M2), "\n", M1.transpose())
print(M2.reshape(-1), M2[0], M2[1, 1])


[[1 2 3]
 [4 5 6]
 [7 8 9]] 
 [[1 0 0]
 [0 2 0]
 [0 0 1]] 3
[[ 2  2  3]
 [ 4  7  6]
 [ 7  8 10]] 
 [[0 2 3]
 [4 3 6]
 [7 8 8]]
[[ 1  4  3]
 [ 4 10  6]
 [ 7 16  9]] 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
[1 0 0 0 2 0 0 0 1] [1 0 0] 2


In [17]:
# More Question
# Question : Solve the equation A*X = B with A and B is defined matrix ?


In [19]:
A = np.array([[2, 3],
              [5, -3]])
B = np.array([5, 6])
# X=Ar.B
AR = np.linalg.inv(A)

X = AR.dot(B)
# check
C = np.dot(A, X)-B
print(C)


[ 0.00000000e+00 -1.77635684e-15]


In [20]:
# DataFrame
import pandas as pd

lst = {'Geeks', 'For', 'Geeks', 'is', 'portal', 'for', 'Geeks'}
df1 = pd.DataFrame(lst)
df1.columns = ["Attribute"]
display(df1)
print(type(lst), type(df1))

data = {'Name': ['Tom', 'nick', 'krish', 'jack'],
        'Age': [20, 21, 19, 18]}
df2 = pd.DataFrame(data)
display(df2)
print(type(data), type(df2))

sales = [{'account': 'Jones LLC', 'Jan': 150, 'Feb': 200, 'Mar': 140},
         {'account': 'Alpha Co',  'Jan': 200, 'Feb': 210, 'Mar': 215},
         {'account': 'Blue Inc',  'Jan': 50,  'Feb': 90,  'Mar': 95}]
df3 = pd.DataFrame(sales)
display(df3)
print(type(sales), type(df3))

s = pd.Series({'USA': 'New York', 'VietNam': 'HCM City', 'Korea': 'Seoul'})
df4 = pd.DataFrame({'Country': s.index, 'Capital': s.values})
display(df4)
print(type(s), type(df4))


Attribute
0    portal
1        is
2     Geeks
3       For
4       for

<class 'set'> <class 'pandas.core.frame.DataFrame'>


Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18

<class 'dict'> <class 'pandas.core.frame.DataFrame'>


account  Jan  Feb  Mar
0  Jones LLC  150  200  140
1   Alpha Co  200  210  215
2   Blue Inc   50   90   95

<class 'list'> <class 'pandas.core.frame.DataFrame'>


Country   Capital
0      USA  New York
1  VietNam  HCM City
2    Korea     Seoul

<class 'pandas.core.series.Series'> <class 'pandas.core.frame.DataFrame'>


In [21]:
import os
path_Data = "E:/MSE/HomeWork/Python/Buoi1/OnClass/B/Stock Market/"
checkPath = os.path.isdir(path_Data)
checkFile = os.path.isfile(path_Data + "AAPL.csv")
print("The path and file are valid or not :", checkPath, checkFile)


The path and file are valid or not : True True


In [22]:
df = pd.read_csv(path_Data + "AAPL.csv")
display(df.head())


Date       High        Low       Open      Close     Volume  \
0  12/30/2019  73.172501  71.305000  72.364998  72.879997  144114400   
1  12/31/2019  73.419998  72.379997  72.482498  73.412498  100805600   
2    1/2/2020  75.150002  73.797501  74.059998  75.087502  135480400   
3    1/3/2020  75.144997  74.125000  74.287498  74.357498  146322800   
4    1/6/2020  74.989998  73.187500  73.447502  74.949997  118387200   

   Adj Close  
0  72.255997  
1  72.783936  
2  74.444603  
3  73.720840  
4  74.308266

In [23]:
# More Question
# Question : How to read txt, xls file and csv file without header  ?


In [26]:
# DataFrame
import seaborn as sns
df = sns.load_dataset('titanic')
s = df['class']
lst = df['age'].to_list()
subdf = df.loc[:, ['sex', 'class']]

display(df.head(3))
display(df.tail(3))
print(s)
print(lst)
print(type(df), type(s), type(lst))
display(subdf.head())


survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True

survived  pclass     sex   age  sibsp  parch   fare embarked  class  \
888         0       3  female   NaN      1      2  23.45        S  Third   
889         1       1    male  26.0      0      0  30.00        C  First   
890         0       3    male  32.0      0      0   7.75        Q  Third   

       who  adult_male deck  embark_town alive  alone  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True

0       Third
1       First
2       Third
3       First
4       Third
        ...  
886    Second
887     First
888     Third
889     First
890     Third
Name: class, Length: 891, dtype: category
Categories (3, object): ['First', 'Second', 'Third']
[22.0, 38.0, 26.0, 35.0, 35.0, nan, 54.0, 2.0, 27.0, 14.0, 4.0, 58.0, 20.0, 39.0, 14.0, 55.0, 2.0, nan, 31.0, nan, 35.0, 34.0, 15.0, 28.0, 8.0, 38.0, nan, 19.0, nan, nan, 40.0, nan, nan, 66.0, 28.0, 42.0, nan, 21.0, 18.0, 14.0, 40.0, 27.0, nan, 3.0, 19.0, nan, nan, nan, nan, 18.0, 7.0, 21.0, 49.0, 29.0, 65.0, nan, 21.0, 28.5, 5.0, 11.0, 22.0, 38.0, 45.0, 4.0, nan, nan, 29.0, 19.0, 17.0, 26.0, 32.0, 16.0, 21.0, 26.0, 32.0, 25.0, nan, nan, 0.83, 30.0, 22.0, 29.0, nan, 28.0, 17.0, 33.0, 16.0, nan, 23.0, 24.0, 29.0, 20.0, 46.0, 26.0, 59.0, nan, 71.0, 23.0, 34.0, 34.0, 28.0, nan, 21.0, 33.0, 37.0, 28.0, 21.0, nan, 38.0, nan, 47.0, 14.5, 22.0, 20.0, 17.0, 21.0, 70.5, 29.0, 24.0, 2.0, 21.0, nan, 32.5, 32.5, 54.0, 12.0, nan, 24.0, nan, 45.0, 33.0, 2

sex  class
0    male  Third
1  female  First
2  female  Third
3  female  First
4    male  Third

In [27]:
# DataFrame :
ListRow01 = [0, 5, 7]
ListRow02 = list(range(3, 9))
ListCol = ['class', 'sex', 'age', 'fare', 'who']

df1 = df[ListCol]
df2 = df.loc[ListRow01]
df3 = df.loc[ListRow02, ListCol]

display(df1.head())
display(df2.head())
display(df3.head())


class     sex   age     fare    who
0  Third    male  22.0   7.2500    man
1  First  female  38.0  71.2833  woman
2  Third  female  26.0   7.9250  woman
3  First  female  35.0  53.1000  woman
4  Third    male  35.0   8.0500    man

survived  pclass   sex   age  sibsp  parch     fare embarked  class    who  \
0         0       3  male  22.0      1      0   7.2500        S  Third    man   
5         0       3  male   NaN      0      0   8.4583        Q  Third    man   
7         0       3  male   2.0      3      1  21.0750        S  Third  child   

   adult_male deck  embark_town alive  alone  
0        True  NaN  Southampton    no  False  
5        True  NaN   Queenstown    no   True  
7       False  NaN  Southampton    no  False

class     sex   age     fare    who
3  First  female  35.0  53.1000  woman
4  Third    male  35.0   8.0500    man
5  Third    male   NaN   8.4583    man
6  First    male  54.0  51.8625    man
7  Third    male   2.0  21.0750  child

In [28]:
# DataFrame
Condition01 = df["age"] < 20
Condition02 = df["sex"] == "male"
Condition03 = df["alone"] == True

df01 = df[Condition01 & Condition02]
df02 = df[Condition01 | Condition02]

print(Condition01)
display(df01.head(), df01.shape)
display(df02.head(), df02.shape)


0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887     True
888    False
889    False
890    False
Name: age, Length: 891, dtype: bool


survived  pclass   sex   age  sibsp  parch      fare embarked  class  \
7          0       3  male   2.0      3      1   21.0750        S  Third   
16         0       3  male   2.0      4      1   29.1250        Q  Third   
27         0       1  male  19.0      3      2  263.0000        S  First   
50         0       3  male   7.0      4      1   39.6875        S  Third   
59         0       3  male  11.0      5      2   46.9000        S  Third   

      who  adult_male deck  embark_town alive  alone  
7   child       False  NaN  Southampton    no  False  
16  child       False  NaN   Queenstown    no  False  
27    man        True    C  Southampton    no  False  
50  child       False  NaN  Southampton    no  False  
59  child       False  NaN  Southampton    no  False

(89, 15)

survived  pclass   sex   age  sibsp  parch     fare embarked  class    who  \
0         0       3  male  22.0      1      0   7.2500        S  Third    man   
4         0       3  male  35.0      0      0   8.0500        S  Third    man   
5         0       3  male   NaN      0      0   8.4583        Q  Third    man   
6         0       1  male  54.0      0      0  51.8625        S  First    man   
7         0       3  male   2.0      3      1  21.0750        S  Third  child   

   adult_male deck  embark_town alive  alone  
0        True  NaN  Southampton    no  False  
4        True  NaN  Southampton    no   True  
5        True  NaN   Queenstown    no   True  
6        True    E  Southampton    no   True  
7       False  NaN  Southampton    no  False

(652, 15)